version: '3.8' # Use 3.8 for standard stability, or leave blank for Spec
services:
  playwright-test:
    build: 
      context: .
      dockerfile: ./Dockerfile   
    # These must be indented under the service name!
    command: npm run productPage-chromium
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results